"""empty message

Revision ID: 32389412698c
Revises: db4ae1152e5a
Create Date: 2017-10-24 16:21:49.933146

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32389412698c'
down_revision = 'db4ae1152e5a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('content_en', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('content_sv', sa.Text(), nullable=True))

    op.execute("UPDATE post SET content_sv = content")

    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_column('content')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('content', sa.TEXT(), nullable=True))
        batch_op.drop_column('content_sv')
        batch_op.drop_column('content_en')

    # ### end Alembic commands ###
