"""empty message

Revision ID: b331923cc85b
Revises: 32389412698c
Create Date: 2018-05-03 11:46:17.923502

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b331923cc85b'
down_revision = '32389412698c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('readmore_en', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('readmore_sv', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_column('readmore_sv')
        batch_op.drop_column('readmore_en')

    # ### end Alembic commands ###
